version: "2.4"

services:


networks:
  my-app:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-myapp
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

volumes:
  mybdd:


